server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  main:
    allow-bean-definition-overriding: true


  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin

  application:
    name: transactions-ms
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    
application:
  async:
    corePoolSize: 20
    maxPoolSize: 40
    queueCapacity: 60

  locale:
    country: BR
    language: pt

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - scheduledtasks
          - heapdump
          - mappings
          - env
          - flyway
          - configprops
          - shutdown
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      apache: WARN
    root: info

business:
  payments:
    endpoint: http://localhost:9081/payments/v1/

